from src.data_deidentifier.domain.exceptions import DataDeidentifierError


class AnalyzeError(DataDeidentifierError):
    """Raised when an error occurs during the analysis process."""
